#!/usr/bin/env python3
"""Run every analysis SQL file and regenerate all exported CSVs and key metrics.

Usage (after scripts/ingest.py):
    python scripts/export_all.py

Every number in data/insights/key_metrics.md is written by this script from the
database. The first version of that file was written by hand and contained
figures that did not match the data.
"""

from __future__ import annotations

import sys
from pathlib import Path

import pandas as pd
import psycopg2

sys.path.insert(0, str(Path(__file__).parent))
from db import DB_CONFIG  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
SQL = ROOT / "sql"
EXPORTS = ROOT / "data" / "exports"
INSIGHTS = ROOT / "data" / "insights"

SQL_EXPORTS = {
    "01_data_quality.sql": "data_quality_report.csv",
    "02_revenue_trend.sql": "revenue_trend.csv",
    "03_rfm_segmentation.sql": "rfm_segmentation.csv",
    "04_shipping_performance.sql": "shipping_performance.csv",
    "05_payment_analysis.sql": "payment_analysis.csv",
    "06_category_analysis.sql": "category_analysis.csv",
}
VIEW_EXPORTS = {
    "vw_dashboard_executive": "dashboard_kpis.csv",
    "vw_dashboard_orders": "dashboard_executive.csv",
    "vw_revenue_monthly": "dashboard_revenue_monthly.csv",
    "vw_rfm_summary": "dashboard_rfm_summary.csv",
    "vw_shipping_summary": "dashboard_shipping_summary.csv",
}

KEY_METRICS_SQL = """
WITH o AS (
    SELECT o.order_id, o.status, o.order_timestamp, o.timestamp_is_estimated,
           p.payment_method, p.total_payment, c.province, c.city
    FROM orders o
    JOIN payments p USING (order_id)
    JOIN customers c USING (customer_id)
)
SELECT
    COUNT(*)                                                         AS orders_all,
    SUM((status = 'Selesai')::int)                                   AS orders_completed,
    SUM((status = 'Batal')::int)                                     AS orders_cancelled,
    SUM(timestamp_is_estimated::int)                                 AS orders_estimated_timestamp,
    SUM(CASE WHEN status = 'Selesai' THEN total_payment END)         AS revenue_completed,
    AVG(CASE WHEN status = 'Selesai' THEN total_payment END)         AS aov_completed,
    AVG((payment_method ILIKE 'COD%')::int)                          AS cod_share_orders,
    SUM(CASE WHEN status = 'Selesai' AND payment_method ILIKE 'COD%' THEN total_payment END)
      / SUM(CASE WHEN status = 'Selesai' THEN total_payment END)     AS cod_share_revenue,
    COUNT(DISTINCT city || '|' || province)                          AS buyer_locations,
    MIN(order_timestamp)::date                                       AS first_order,
    MAX(order_timestamp)::date                                       AS last_order
FROM o
"""

PROVINCE_SQL = """
SELECT c.province, SUM(p.total_payment) AS revenue
FROM orders o JOIN payments p USING (order_id) JOIN customers c USING (customer_id)
WHERE o.status = 'Selesai'
GROUP BY 1 ORDER BY 2 DESC
"""


def query(conn, sql: str) -> pd.DataFrame:
    with conn.cursor() as cur:
        cur.execute(sql)
        cols = [d[0] for d in cur.description]
        return pd.DataFrame(cur.fetchall(), columns=cols)


def rupiah(x: float) -> str:
    return f"Rp {x:,.0f}".replace(",", ".")


def write_key_metrics(conn) -> None:
    k = query(conn, KEY_METRICS_SQL).iloc[0]
    prov = query(conn, PROVINCE_SQL)
    prov["share"] = prov["revenue"].astype(float) / float(prov["revenue"].sum())
    rfm = query(conn, "SELECT * FROM vw_rfm_summary")
    lines = [
        "# Key metrics (generated)",
        "",
        "Generated by `scripts/export_all.py` from the PostgreSQL tables (no run date, so re-runs on the same data give an identical file).",
        "Do not edit by hand.",
        "",
        f"- Period: {k.first_order} to {k.last_order}",
        f"- Orders: {int(k.orders_all):,} total, {int(k.orders_completed):,} completed (Selesai), "
        f"{int(k.orders_cancelled):,} cancelled (Batal)",
        f"- Orders dated from the export file name (no timestamp in source): {int(k.orders_estimated_timestamp):,}",
        f"- Revenue from completed orders: {rupiah(float(k.revenue_completed))}",
        f"- Average completed order value: {rupiah(float(k.aov_completed))}",
        f"- COD share: {float(k.cod_share_orders):.1%} of all orders, "
        f"{float(k.cod_share_revenue):.1%} of completed revenue",
        f"- Buyer locations (city/regency + province): {int(k.buyer_locations):,}. "
        "The data has no buyer ID, so these are locations, not customers.",
        "",
        "## Revenue by province (completed orders)",
        "",
        "| Rank | Province | Revenue | Share | Cumulative |",
        "|---:|---|---:|---:|---:|",
    ]
    cum = 0.0
    for i, r in prov.head(10).iterrows():
        cum += r.share
        lines.append(f"| {i + 1} | {r.province} | {rupiah(float(r.revenue))} | {r.share:.1%} | {cum:.1%} |")
    lines += ["", "## RFM segments of buyer locations", "",
              "| Segment | Locations | Share of locations | Share of revenue |", "|---|---:|---:|---:|"]
    for _, r in rfm.iterrows():
        lines.append(f"| {r.segment} | {int(r.customer_count)} | {float(r.customer_pct):.1f}% "
                     f"| {float(r.revenue_pct):.1f}% |")
    INSIGHTS.mkdir(parents=True, exist_ok=True)
    (INSIGHTS / "key_metrics.md").write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    EXPORTS.mkdir(parents=True, exist_ok=True)
    with psycopg2.connect(**DB_CONFIG) as conn:
        for sql_file, csv_name in SQL_EXPORTS.items():
            df = query(conn, (SQL / sql_file).read_text(encoding="utf-8"))
            df.to_csv(EXPORTS / csv_name, index=False)
            print(f"{sql_file:<32} -> {csv_name:<32} {len(df):>6} rows")
        with conn.cursor() as cur:
            cur.execute((SQL / "07_views_dashboard_prep.sql").read_text(encoding="utf-8"))
        for view, csv_name in VIEW_EXPORTS.items():
            df = query(conn, f"SELECT * FROM {view}")
            df.to_csv(EXPORTS / csv_name, index=False)
            print(f"{view:<32} -> {csv_name:<32} {len(df):>6} rows")
        write_key_metrics(conn)
        print("data/insights/key_metrics.md written")


if __name__ == "__main__":
    main()
